Repository SonJuMoney/FE_SonjuMoney, pull requests merged in 2025-02, with the labels that each got.

#158 [#126] fix : 통화 끊기, 카메라 끄기 수정 중
  components/Calls/MeetingRoom.tsx
Labels: bug

#177 Develop
  app/(routes)/register/account/page.tsx
Labels: bug, bug fixed

#179 Develop
  app/(routes)/allowance/[id]/message/MessageForm.tsx
  app/(routes)/allowance/send/password/page.tsx
  app/(routes)/allowance/send/response/page.tsx
  app/(routes)/calendar/add/page.tsx
  app/(routes)/calendar/detail/[eventId]/page.tsx
  app/(routes)/calendar/update/[eventId]/page.tsx
  app/(routes)/home/sections/NotificationSection.tsx
  app/(routes)/register/child/page.tsx
  app/(routes)/register/family/invite/page.tsx
  app/(routes)/savings/member/page.tsx
  app/(routes)/savings/send/page.tsx
  app/(routes)/signup/page.tsx
  app/(routes)/signup/setPin/page.tsx
  app/actions/accounts.ts
  app/actions/allowance.ts
  app/actions/createFeed.ts
  app/actions/family.ts
  app/actions/savings.ts
  app/actions/stream.actions.ts
  components/Calls/MeetingRoom.tsx
  components/LoginForm.tsx
  components/atoms/Buttons/ProfileButton.tsx
  components/atoms/Cards/AlarmCard.tsx
  components/molecules/Cards/PlanCard.tsx
  components/molecules/FeedCard/CommentDrawer.tsx
  components/molecules/Forms/LoginForm.tsx
  components/molecules/Forms/PasswordForm.tsx
  components/molecules/Lists/RoleList.tsx
  hooks/useAccountApi/useAccountApi.ts
  hooks/useApi.ts
  hooks/useFamilyApi/useFamilyApi.ts
  hooks/useSavingApi/useSavingApi.ts
  lib/auth.ts
  lib/websocket.ts
  providers/NotificationProvider.tsx
Labels: style

#181 Develop
  app/(routes)/register/child/page.tsx
  app/(routes)/signup/page.tsx
  app/(routes)/signup/setPin/page.tsx
Labels: bug

#182 [#126] fix : 캘린더 알림 라우팅 수정
  lib/alarm.ts
Labels: bug fixed

#183 Develop
  lib/alarm.ts
Labels: bug fixed

#187 Develop
  components/atoms/Buttons/ProfileButton.tsx
  components/atoms/Cards/AlarmCard.tsx
  lib/auth.ts
  types/Alarm.ts
Labels: bug fixed

#188 J0j00h patch 1
  README.md
Labels: merge

#189 Develop
  README.md
Labels: feat

#191 Develop
  app/not-found.tsx
  components/Calls/MeetingRoom.tsx
  components/Calls/MeetingSetup.tsx
  components/atoms/Alarm/Alarm.tsx
  components/atoms/Buttons/ProfileButton.tsx
Labels: bug fixed
